parameters:
    database_driver: pdo_mysql
    database_host: MYSQL_HOST
    database_port: MYSQL_PORT
    database_name: MYSQL_DATABASE
    database_user: MYSQL_USER
    database_password: MYSQL_PASSWORD
    database_driver_options: {  }
    mailer_transport: APP_MAILER_TRANSPORT
    mailer_host: APP_MAILER_HOST
    mailer_port: APP_MAILER_PORT
    mailer_encryption: APP_MAILER_ENCRYPTION
    mailer_user: APP_MAILER_USER
    mailer_password: APP_MAILER_PASSWORD
    websocket_bind_address: 0.0.0.0
    websocket_bind_port: 8080
    websocket_frontend_host: '*'
    websocket_frontend_port: 8080
    websocket_frontend_path: 'ws'
    websocket_backend_host: '*'
    websocket_backend_port: 8080
    websocket_backend_path: ''
    websocket_backend_transport: tcp
    websocket_backend_ssl_context_options: {  }
    web_backend_prefix: /admin
    session_handler: session.handler.native_file
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    installed: false
    assets_version: null
    assets_version_strategy: time_hash
    message_queue_transport: dbal
    message_queue_transport_config: null
    enable_price_sharding: false

